import type { Loan } from "@/types/loan";

export const mockLoans: Loan[] = [
{
id: 1,
name: "India Loan",
loanType: "loan",
lender: "Personal",
currentBalance: 36265,
totalPaid: 0,
monthlyPayment: 1500,
annualInterestRate: 10.5,
monthlyFee: 0,
dueDay: 5,
isAutopay: true,
notes: "",
monthsToPayoff: 28,
yearsToPayoff: 2,
remainingMonths: 4,
totalInterest: 4660,
totalFees: 0,
totalPayable: 40925,
totalCost: 4660,
isActive: true,
},
{
id: 2,
name: "Education",
loanType: "loan",
lender: "Bank",
currentBalance: 28596,
totalPaid: 0,
monthlyPayment: 612,
annualInterestRate: 9.3,
monthlyFee: 0,
dueDay: 10,
isAutopay: true,
notes: "",
monthsToPayoff: 59,
yearsToPayoff: 4,
remainingMonths: 11,
totalInterest: 7046,
totalFees: 0,
totalPayable: 35642,
totalCost: 7046,
isActive: true,
},
{
id: 3,
name: "Keyboard Spar",
loanType: "emi",
lender: "Spar",
currentBalance: 9559,
totalPaid: 0,
monthlyPayment: 225,
annualInterestRate: 9.06,
monthlyFee: 0,
dueDay: 15,
isAutopay: true,
notes: "",
monthsToPayoff: 52,
yearsToPayoff: 4,
remainingMonths: 4,
totalInterest: 2011,
totalFees: 0,
totalPayable: 11570,
totalCost: 2011,
isActive: true,
},
{
id: 4,
name: "SparExpress",
loanType: "loan",
lender: "Spar",
currentBalance: 47817,
totalPaid: 0,
monthlyPayment: 1466,
annualInterestRate: 8.84,
monthlyFee: 0,
dueDay: 20,
isAutopay: true,
notes: "",
monthsToPayoff: 38,
yearsToPayoff: 3,
remainingMonths: 2,
totalInterest: 7073,
totalFees: 0,
totalPayable: 54890,
totalCost: 7073,
isActive: true,
},
{
id: 5,
name: "Mac Resurs",
loanType: "emi",
lender: "Resurs",
currentBalance: 7904,
totalPaid: 0,
monthlyPayment: 836,
annualInterestRate: 0,
monthlyFee: 0,
dueDay: 25,
isAutopay: true,
notes: "",
monthsToPayoff: 10,
yearsToPayoff: 0,
remainingMonths: 10,
totalInterest: 0,
totalFees: 0,
totalPayable: 7904,
totalCost: 0,
isActive: true,
},
{
id: 6,
name: "Sofa Resurs",
loanType: "emi",
lender: "Resurs",
currentBalance: 10349,
totalPaid: 0,
monthlyPayment: 564,
annualInterestRate: 0,
monthlyFee: 0,
dueDay: 25,
isAutopay: true,
notes: "Interest/fee needs verification",
monthsToPayoff: 19,
yearsToPayoff: 1,
remainingMonths: 7,
totalInterest: 0,
totalFees: 0,
totalPayable: 10349,
totalCost: 0,
isActive: true,
},
{
id: 7,
name: "iPad PayX",
loanType: "bnpl",
lender: "PayX",
currentBalance: 2846,
totalPaid: 0,
monthlyPayment: 409,
annualInterestRate: 0,
monthlyFee: 0,
dueDay: 1,
isAutopay: true,
notes: "",
monthsToPayoff: 7,
yearsToPayoff: 0,
remainingMonths: 7,
totalInterest: 0,
totalFees: 0,
totalPayable: 2846,
totalCost: 0,
isActive: true,
},
];
