/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChartsRouteImport } from './routes/charts'
import { Route as AddRouteImport } from './routes/add'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SavingsIndexRouteImport } from './routes/savings.index'
import { Route as LoansIndexRouteImport } from './routes/loans.index'
import { Route as SavingsAddRouteImport } from './routes/savings.add'
import { Route as LoansAddRouteImport } from './routes/loans.add'
import { Route as LoansLoanIdRouteImport } from './routes/loans.$loanId'
import { Route as ExpensesAddRouteImport } from './routes/expenses.add'
import { Route as LoansLoanIdIndexRouteImport } from './routes/loans.$loanId.index'
import { Route as LoansLoanIdEditRouteImport } from './routes/loans.$loanId.edit'
import { Route as ChartsCategoryCategoryRouteImport } from './routes/charts.category.$category'

const ChartsRoute = ChartsRouteImport.update({
  id: '/charts',
  path: '/charts',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SavingsIndexRoute = SavingsIndexRouteImport.update({
  id: '/savings/',
  path: '/savings/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansIndexRoute = LoansIndexRouteImport.update({
  id: '/loans/',
  path: '/loans/',
  getParentRoute: () => rootRouteImport,
} as any)
const SavingsAddRoute = SavingsAddRouteImport.update({
  id: '/savings/add',
  path: '/savings/add',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansAddRoute = LoansAddRouteImport.update({
  id: '/loans/add',
  path: '/loans/add',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansLoanIdRoute = LoansLoanIdRouteImport.update({
  id: '/loans/$loanId',
  path: '/loans/$loanId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesAddRoute = ExpensesAddRouteImport.update({
  id: '/expenses/add',
  path: '/expenses/add',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansLoanIdIndexRoute = LoansLoanIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoansLoanIdRoute,
} as any)
const LoansLoanIdEditRoute = LoansLoanIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => LoansLoanIdRoute,
} as any)
const ChartsCategoryCategoryRoute = ChartsCategoryCategoryRouteImport.update({
  id: '/category/$category',
  path: '/category/$category',
  getParentRoute: () => ChartsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/charts': typeof ChartsRouteWithChildren
  '/expenses/add': typeof ExpensesAddRoute
  '/loans/$loanId': typeof LoansLoanIdRouteWithChildren
  '/loans/add': typeof LoansAddRoute
  '/savings/add': typeof SavingsAddRoute
  '/loans/': typeof LoansIndexRoute
  '/savings/': typeof SavingsIndexRoute
  '/charts/category/$category': typeof ChartsCategoryCategoryRoute
  '/loans/$loanId/edit': typeof LoansLoanIdEditRoute
  '/loans/$loanId/': typeof LoansLoanIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/charts': typeof ChartsRouteWithChildren
  '/expenses/add': typeof ExpensesAddRoute
  '/loans/add': typeof LoansAddRoute
  '/savings/add': typeof SavingsAddRoute
  '/loans': typeof LoansIndexRoute
  '/savings': typeof SavingsIndexRoute
  '/charts/category/$category': typeof ChartsCategoryCategoryRoute
  '/loans/$loanId/edit': typeof LoansLoanIdEditRoute
  '/loans/$loanId': typeof LoansLoanIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/charts': typeof ChartsRouteWithChildren
  '/expenses/add': typeof ExpensesAddRoute
  '/loans/$loanId': typeof LoansLoanIdRouteWithChildren
  '/loans/add': typeof LoansAddRoute
  '/savings/add': typeof SavingsAddRoute
  '/loans/': typeof LoansIndexRoute
  '/savings/': typeof SavingsIndexRoute
  '/charts/category/$category': typeof ChartsCategoryCategoryRoute
  '/loans/$loanId/edit': typeof LoansLoanIdEditRoute
  '/loans/$loanId/': typeof LoansLoanIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add'
    | '/charts'
    | '/expenses/add'
    | '/loans/$loanId'
    | '/loans/add'
    | '/savings/add'
    | '/loans/'
    | '/savings/'
    | '/charts/category/$category'
    | '/loans/$loanId/edit'
    | '/loans/$loanId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add'
    | '/charts'
    | '/expenses/add'
    | '/loans/add'
    | '/savings/add'
    | '/loans'
    | '/savings'
    | '/charts/category/$category'
    | '/loans/$loanId/edit'
    | '/loans/$loanId'
  id:
    | '__root__'
    | '/'
    | '/add'
    | '/charts'
    | '/expenses/add'
    | '/loans/$loanId'
    | '/loans/add'
    | '/savings/add'
    | '/loans/'
    | '/savings/'
    | '/charts/category/$category'
    | '/loans/$loanId/edit'
    | '/loans/$loanId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRoute: typeof AddRoute
  ChartsRoute: typeof ChartsRouteWithChildren
  ExpensesAddRoute: typeof ExpensesAddRoute
  LoansLoanIdRoute: typeof LoansLoanIdRouteWithChildren
  LoansAddRoute: typeof LoansAddRoute
  SavingsAddRoute: typeof SavingsAddRoute
  LoansIndexRoute: typeof LoansIndexRoute
  SavingsIndexRoute: typeof SavingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/charts': {
      id: '/charts'
      path: '/charts'
      fullPath: '/charts'
      preLoaderRoute: typeof ChartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/savings/': {
      id: '/savings/'
      path: '/savings'
      fullPath: '/savings/'
      preLoaderRoute: typeof SavingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans/': {
      id: '/loans/'
      path: '/loans'
      fullPath: '/loans/'
      preLoaderRoute: typeof LoansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/savings/add': {
      id: '/savings/add'
      path: '/savings/add'
      fullPath: '/savings/add'
      preLoaderRoute: typeof SavingsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans/add': {
      id: '/loans/add'
      path: '/loans/add'
      fullPath: '/loans/add'
      preLoaderRoute: typeof LoansAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans/$loanId': {
      id: '/loans/$loanId'
      path: '/loans/$loanId'
      fullPath: '/loans/$loanId'
      preLoaderRoute: typeof LoansLoanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses/add': {
      id: '/expenses/add'
      path: '/expenses/add'
      fullPath: '/expenses/add'
      preLoaderRoute: typeof ExpensesAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans/$loanId/': {
      id: '/loans/$loanId/'
      path: '/'
      fullPath: '/loans/$loanId/'
      preLoaderRoute: typeof LoansLoanIdIndexRouteImport
      parentRoute: typeof LoansLoanIdRoute
    }
    '/loans/$loanId/edit': {
      id: '/loans/$loanId/edit'
      path: '/edit'
      fullPath: '/loans/$loanId/edit'
      preLoaderRoute: typeof LoansLoanIdEditRouteImport
      parentRoute: typeof LoansLoanIdRoute
    }
    '/charts/category/$category': {
      id: '/charts/category/$category'
      path: '/category/$category'
      fullPath: '/charts/category/$category'
      preLoaderRoute: typeof ChartsCategoryCategoryRouteImport
      parentRoute: typeof ChartsRoute
    }
  }
}

interface ChartsRouteChildren {
  ChartsCategoryCategoryRoute: typeof ChartsCategoryCategoryRoute
}

const ChartsRouteChildren: ChartsRouteChildren = {
  ChartsCategoryCategoryRoute: ChartsCategoryCategoryRoute,
}

const ChartsRouteWithChildren =
  ChartsRoute._addFileChildren(ChartsRouteChildren)

interface LoansLoanIdRouteChildren {
  LoansLoanIdEditRoute: typeof LoansLoanIdEditRoute
  LoansLoanIdIndexRoute: typeof LoansLoanIdIndexRoute
}

const LoansLoanIdRouteChildren: LoansLoanIdRouteChildren = {
  LoansLoanIdEditRoute: LoansLoanIdEditRoute,
  LoansLoanIdIndexRoute: LoansLoanIdIndexRoute,
}

const LoansLoanIdRouteWithChildren = LoansLoanIdRoute._addFileChildren(
  LoansLoanIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRoute: AddRoute,
  ChartsRoute: ChartsRouteWithChildren,
  ExpensesAddRoute: ExpensesAddRoute,
  LoansLoanIdRoute: LoansLoanIdRouteWithChildren,
  LoansAddRoute: LoansAddRoute,
  SavingsAddRoute: SavingsAddRoute,
  LoansIndexRoute: LoansIndexRoute,
  SavingsIndexRoute: SavingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
